# Generated by Django 3.1.6 on 2021-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VarDBapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathogenicity',
            name='pathogenicity_code',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True),
        ),
    ]
